const fs = require('fs');
let content = fs.readFileSync('js/index-B3R5Kdbb.js', 'utf8');

// 1. RSVP check box section
const rsvpStartStr = '}) : h.jsxs(h.Fragment, {\n                        children: [h.jsxs("div", {\n                            className: "space-y-3",\n                            children: [h.jsx(Xe, {';
const rsvpStartIdx = content.indexOf('className: "space-y-3",\\n                            children: [h.jsx(Xe, {\\n                                className: "text-foreground font-body text-base tracking-wide",\\n                                children: e("rsvp.whichEvents")');
// Better way: use regex that ignores whitespace
content = content.replace(/h\.jsxs\(\"div\",\s*\{\s*className:\s*\"space-y-3\",\s*children:\s*\[h\.jsx\(Xe,\s*\{\s*className:\s*\"text-foreground font-body text-base tracking-wide\",\s*children:\s*e\(\"rsvp\.whichEvents\"\)\s*\}\),\s*h\.jsx\(\"div\",\s*\{\s*className:\s*\"space-y-2\",\s*children:\s*t\.map\(R\s*=>\s*h\.jsxs\(\"div\",\s*\{\s*className:\s*\"flex items-center space-x-3\",\s*children:\s*\[h\.jsx\(RT,\s*\{\s*id:\s*\`event-\$\{R\.id\}\`,\s*checked:\s*f\.includes\(R\.id\),\s*onCheckedChange:\s*\(\)\s*=>\s*_\(R\.id\),\s*className:\s*\"border-foreground\/30 data-\[state=checked\]:bg-foreground data-\[state=checked\]:border-foreground\"\s*\}\),\s*h\.jsx\(Xe,\s*\{\s*htmlFor:\s*\`event-\$\{R\.id\}\`,\s*className:\s*\"cursor-pointer text-foreground font-body text-base\",\s*children:\s*R\.label\s*\}\)\]\s*\},\s*R\.id\)\)\s*\}\)\]\s*\}\),/s, '');

// 2. Dress Code section
content = content.replace(/h\.jsxs\(he\.div,\s*\{\s*initial:\s*\{\s*opacity:\s*0,\s*y:\s*20\s*\},\s*whileInView:\s*\{\s*opacity:\s*1,\s*y:\s*0\s*\},\s*viewport:\s*\{\s*once:\s*!0\s*\},\s*transition:\s*\{\s*duration:\s*\.6,\s*delay:\s*\.2\s*\},\s*className:\s*\"text-center\",\s*children:\s*\[h\.jsx\(\"h2\",\s*\{\s*className:\s*\"font-display text-5xl md:text-7xl text-foreground mb-10\",\s*children:\s*\"Dress Code\"\s*\}\),\s*h\.jsx\(\"div\",\s*\{\s*className:\s*\"space-y-8\",\s*children:\s*aF\.map\(e\s*=>\s*h\.jsxs\(\"div\",\s*\{\s*className:\s*\"bg-foreground\/\[0\.03\] border border-foreground\/10 rounded-2xl px-6 py-10 md:px-10 md:py-14\",\s*children:\s*\[h\.jsx\(\"h3\",\s*\{\s*className:\s*\"font-display text-4xl md:text-5xl text-foreground mb-1 leading-tight\",\s*children:\s*e\.title\s*\}\),\s*h\.jsx\(\"p\",\s*\{\s*className:\s*\"font-body text-sm tracking-\[0\.25em\] uppercase text-foreground\/50 mb-4\",\s*children:\s*e\.date\s*\}\),\s*h\.jsx\(\"p\",\s*\{\s*className:\s*\"font-body text-lg tracking-\[0\.1em\] text-foreground\",\s*children:\s*e\.attire\s*\}\),\s*e\.palette\s*&&\s*h\.jsx\(\"div\",\s*\{\s*className:\s*\"mt-5 flex justify-center items-start gap-3 flex-nowrap\",\s*children:\s*e\.palette\.map\(t\s*=>\s*h\.jsxs\(\"div\",\s*\{\s*className:\s*\"flex flex-col items-center gap-1\.5\",\s*children:\s*\[h\.jsx\(\"div\",\s*\{\s*className:\s*\"w-6 h-6 md:w-8 md:h-8 rounded-full shadow-inner overflow-hidden\",\s*style:\s*\{\s*backgroundColor:\s*t\.hex\s*\},\s*children:\s*t\.img\s*&&\s*h\.jsx\(\"img\",\s*\{\s*src:\s*t\.img,\s*alt:\s*t\.name,\s*className:\s*\"w-full h-full object-cover opacity-60 mix-blend-overlay\"\s*\}\)\s*\}\),\s*h\.jsx\(\"span\",\s*\{\s*className:\s*\"font-body text-\[10px\] md:text-xs tracking-wider uppercase text-foreground\/50 text-center whitespace-nowrap\",\s*children:\s*t\.name\s*\}\)\]\s*\},\s*t\.name\)\)\s*\}\)\]\s*\},\s*e\.title\)\)\s*\}\)\]\s*\}\)/s, 'null');

// 3. Your Stay section
// It starts with `h.jsxs(he.h2` ... `children: ["Your ", ... "tay"]`
// Then `h.jsx(he.p` ... `children: "Transportation and accommodation ..."`
// Then `h.jsxs(he.div` ... `children: "Guests will be staying at"` ...
content = content.replace(/h\.jsxs\(he\.h2,\s*\{\s*initial:\s*\{\s*opacity:\s*0,\s*y:\s*20\s*\},\s*whileInView:\s*\{\s*opacity:\s*1,\s*y:\s*0\s*\},\s*viewport:\s*\{\s*once:\s*!0\s*\},\s*transition:\s*\{\s*duration:\s*\.6\s*\},\s*className:\s*\"font-display text-5xl md:text-7xl text-foreground mb-8\",\s*children:\s*\[\"Your \",\s*h\.jsx\(\"span\",\s*\{\s*className:\s*\"script-ornate\",\s*children:\s*\"S\"\s*\}\),\s*\"tay\"\]\s*\}\),\s*h\.jsx\(he\.p,\s*\{\s*initial:\s*\{\s*opacity:\s*0\s*\},\s*whileInView:\s*\{\s*opacity:\s*1\s*\},\s*viewport:\s*\{\s*once:\s*!0\s*\},\s*transition:\s*\{\s*duration:\s*\.6,\s*delay:\s*\.1\s*\},\s*className:\s*\"font-body text-foreground\/70 leading-relaxed max-w-md mx-auto mb-10\",\s*children:\s*\"Transportation and accommodation throughout the engagement celebrations will be lovingly hosted by the couple\.\"\s*\}\),\s*h\.jsxs\(he\.div,\s*\{\s*initial:\s*\{\s*opacity:\s*0,\s*y:\s*20\s*\},\s*whileInView:\s*\{\s*opacity:\s*1,\s*y:\s*0\s*\},\s*viewport:\s*\{\s*once:\s*!0\s*\},\s*transition:\s*\{\s*duration:\s*\.6,\s*delay:\s*\.2\s*\},\s*children:\s*\[h\.jsx\(\"p\",\s*\{\s*className:\s*\"font-body text-sm tracking-\[0\.25em\] uppercase text-foreground\/50 mb-3\",\s*children:\s*\"Guests will be staying at\"\s*\}\),\s*h\.jsxs\(\"h3\",\s*\{\s*className:\s*\"font-display text-4xl md:text-5xl text-foreground leading-tight\",\s*children:\s*\[\"Kinan \",\s*h\.jsx\(\"span\",\s*\{\s*className:\s*\"script-ornate\",\s*children:\s*\"S\"\s*\}\),\s*\"entral\"\]\s*\}\),\s*h\.jsx\(\"a\",\s*\{\s*className:\s*\"font-body text-foreground\/60 italic tracking-wide mt-2\",\s*href:\s*\"https:\/\/maps\.app\.goo\.gl\/btM3xGSjJtN5p6W68\?g_st=iw\",\s*target:\s*\"_blank\",\s*style:\s*\{textDecoration:\s*\"underline\"\},\s*children:\s*\"VIP HALL The Great Sea Street\"\s*\}\),\s*h\.jsx\(ut,\s*\{\s*src:\s*yF\.url,\s*alt:\s*\"Kinan Hotels illustration\",\s*loading:\s*\"lazy\",\s*className:\s*\"w-full max-w-\[320px\] mx-auto h-auto mt-8 select-none\",\s*draggable:\s*!1\s*\}\)\]\s*\}\)/s, 'null, null, null');

fs.writeFileSync('js/index-B3R5Kdbb.js', content);
